// Hallazgos investigados manualmente y respaldados por fuentes públicas.
// Se mantienen separados de la salida automática para conservar su trazabilidad.
export const CURATED_OPPORTUNITIES = [{
  event_key: "CURATED-NOVA-ENERGY-PIRES-2026",
  title: "Nova Energy integra activos de DLS en la Cuenca del Golfo San Jorge",
  source_url: "https://www.adnsur.com.ar/pulso-energetico/los-nuevos-duenos-del-negocio-de-servicios-petroleros-en-la-cuenca-san-jorge--de-la-operacion-y-mantenimiento-al-servicio-de-torrres_a698f9c147c37ca1a1fe72bcb",
  analyzed_at: "2026-09-21T12:00:00.000Z",
  opportunity: {
    relevante: true,
    empresa: "SGA Servicios",
    empresa_prioritaria: true,
    provincia: "Chubut",
    cuenca: "Cuenca del Golfo San Jorge",
    proyecto: "Nova Energy · integración de activos DLS",
    servicios_vermaz: [
      { servicio: "Administración y logística de almacenes", justificacion: "La integración de 24 equipos y una estructura de 750 trabajadores justifica validar necesidades logísticas." },
      { servicio: "Transporte de personal", justificacion: "La continuidad operativa de equipos de workover y pulling requiere movilidad de dotaciones; debe confirmarse el esquema de contratación." },
    ],
    tipo_senal: "Expansión operativa y redistribución de contratos",
    score_radar: 64,
    prioridad: "Media",
    etapa_temporal: "En desarrollo",
    horizonte: "Corto / 1–3 meses",
    hechos_publicados: [
      "Nova Energy está integrada por Vientos del Sur y SGA Servicios, ambas vinculadas a Pires.",
      "La operación transfirió 24 equipos de workover y pulling y aproximadamente 750 trabajadores.",
      "Servicios de operación y mantenimiento de NCY fueron redistribuidos entre SGA, Vientos del Sur y otros accionistas.",
    ],
    inferencias_comerciales: ["Conviene validar si la consolidación requiere apoyo logístico, transporte o administración de materiales."],
    resumen_evidencia: "Expansión operativa documentada de empresas vinculadas a Pires en la Cuenca del Golfo San Jorge.",
    analisis_ia: "Señal estratégica concreta, pero todavía sin licitación publicada para servicios de Vermaz; requiere investigación comercial antes de contactar.",
    area_objetivo: "Operaciones y Abastecimiento",
    cargo_objetivo: "Responsable de Operaciones o Supply Chain",
    persona_objetivo_nombre: "",
    motivo_contacto: "Integración de equipos y contratos operativos en la cuenca.",
    buscar_en_attio: false,
    linkedin_requerido: false,
    mensaje_comercial_sugerido: "",
    tipo_accion: "INVESTIGAR",
    accion_sugerida: "Confirmar el esquema de proveedores de Nova Energy antes de realizar contacto comercial.",
    confianza_ia: 72,
  },
}] as const;

export const CURATED_CONTRACTS = [{
  article_id: "CURATED-MANANTIALES-BEHR-2026",
  source_url: "https://www.abcdiario.com.ar/locales/se-abrio-la-licitacion-en-manantiales-behr-y-garantizan-la-continuidad-laboral-de-los-trabajadores-de-aesa-4091/",
  source_name: "ABC Diario",
  base_end_date: null,
  option_end_date: null,
  expiry_label: "Contrato AESA por finalizar · licitación abierta",
  confidence: 88,
  finding: {
    relevant: true,
    operator: "PECOM",
    provider: "AESA (prestadora saliente)",
    service: "Perforación, workover y pulling · soporte operativo asociado",
    basin: "Cuenca del Golfo San Jorge",
    province: "Chubut",
    evidence: "La licitación ya está en marcha y la fuente informa que la empresa adjudicataria recibirá al personal actualmente perteneciente a AESA, señal de finalización y reemplazo del contrato vigente.",
    confidence_basis: "Transición contractual y licitación abiertas publicadas; la fecha exacta de finalización no es pública.",
  },
}, {
  article_id: "CURATED-TDF-ANGOSTURA-VIOLETAS-RIO-CULLEN-2026",
  source_url: "https://www.tierradelfuego.gob.ar/blog/2026/08/24/tierra-del-fuego-garantiza-la-continuidad-de-la-produccion-y-avanza-hacia-una-nueva-licitacion-en-las-areas-angostura-las-violetas-y-rio-cullen/",
  source_name: "Gobierno de Tierra del Fuego",
  base_end_date: "2026-08-31",
  option_end_date: null,
  expiry_label: "Angostura, Las Violetas y Río Cullen · nueva licitación en preparación",
  radar_status: "OPORTUNIDAD_EN_PREPARACION",
  confidence: 98,
  finding: {
    relevant: true,
    operator: "Roch S.A. por cuenta y orden de la Provincia durante la transición",
    provider: "UTE Roch / Secra / Crown Point Energía / DPG (concesionaria saliente)",
    service: "Operación de yacimientos, logística, almacenes, transporte y soporte de campo",
    basin: "Cuenca Austral",
    province: "Tierra del Fuego",
    evidence: "La Provincia confirmó que la concesión finalizó sin prórroga, mantuvo a Roch como operador transitorio y prepara una licitación para definir al nuevo concesionario de las tres áreas.",
    confidence_basis: "Comunicado oficial provincial del 24/08/2026 con estado, transición, activos y procedimiento futuro explícitos.",
  },
}, {
  article_id: "CURATED-SALTA-PUESTO-GUARDIAN-2026",
  source_url: "https://boletinoficialsalta.gob.ar/boletindigital/2026/22165.pdf",
  source_name: "Boletín Oficial de Salta",
  base_end_date: null,
  option_end_date: null,
  expiry_label: "CNO-8 Puesto Guardián · operación de emergencia previa a nuevo concurso",
  radar_status: "OPORTUNIDAD_EN_PREPARACION",
  confidence: 94,
  finding: {
    relevant: true,
    operator: "REMSa S.A. (operación de emergencia)",
    provider: "Concesionario definitivo a seleccionar",
    service: "Operación, mantenimiento, seguridad, remediación y soporte logístico",
    basin: "Cuenca del Noroeste",
    province: "Salta",
    evidence: "La Resolución 51/2026 aprobó la operación de emergencia por REMSa para asegurar la continuidad operativa, ambiental y de seguridad después de la caducidad de la concesión.",
    confidence_basis: "Acto oficial vigente; la convocatoria definitiva debe monitorearse y no se presenta todavía como licitación abierta.",
  },
}, {
  article_id: "CURATED-RN-PUESTO-FLORES-PRADO-2026",
  source_url: "https://ipross.rionegro.gov.ar/servicio/258/concurso-nacional-internacional-areas-hidrocarburos-rn",
  source_name: "Gobierno de Río Negro",
  base_end_date: "2026-09-04",
  option_end_date: null,
  expiry_label: "Puesto Flores–Estancia Vieja / Puesto Prado · ofertas abiertas; adjudicación pendiente",
  radar_status: "SEGUIMIENTO_DE_ADJUDICACION",
  confidence: 99,
  finding: {
    relevant: true,
    operator: "EDHIPSA durante la transición",
    provider: "Nuevo concesionario en selección",
    service: "Reactivación de áreas maduras, operación, mantenimiento y servicios de campo",
    basin: "Cuenca Neuquina",
    province: "Río Negro",
    evidence: "El Concurso Público Nacional e Internacional 01/26 recibió ofertas hasta el 04/09/2026 y publicó el acta de apertura; la ventana de presentación ya cerró.",
    confidence_basis: "Ficha oficial del concurso y acta de apertura. Debe seguirse la adjudicación, no publicarse como convocatoria todavía abierta.",
  },
}, {
  article_id: "CURATED-SANTA-CRUZ-PUNTA-LOYOLA-2027",
  source_url: "https://boletinoficial.santacruz.gob.ar/legislacion/decretos-completos/31060",
  source_name: "Boletín Oficial de Santa Cruz",
  base_end_date: "2027-11-14",
  option_end_date: null,
  expiry_label: "Terminal marítima Punta Loyola · concesión de transporte vence en 2027",
  radar_status: "VENCIMIENTO_A_VALIDAR",
  confidence: 82,
  finding: {
    relevant: true,
    operator: "YPF S.A.",
    provider: "A definir por la autoridad concedente",
    service: "Operación y mantenimiento de terminal, logística, transporte y soporte industrial",
    basin: "Cuenca Austral",
    province: "Santa Cruz",
    evidence: "El acto provincial localizado fija el vencimiento de la concesión de transporte de la Terminal Marítima Punta Loyola para el 14/11/2027.",
    confidence_basis: "Fuente primaria provincial; antes de promoverla debe descartarse una prórroga o reconversión posterior.",
  },
}, {
  article_id: "CURATED-SALTA-ACAMBUCO-2026",
  source_url: "https://www.salta.gob.ar/prensa/noticias/la-secretaria-de-mineria-realizo-un-recorrido-tecnico-por-la-cuenca-noroeste-107594",
  source_name: "Gobierno de Salta",
  base_end_date: "2026-10-25",
  option_end_date: null,
  expiry_label: "Acambuco · renovación solicitada antes del vencimiento",
  radar_status: "SEGUIMIENTO_REGULATORIO",
  confidence: 92,
  finding: {
    relevant: true,
    operator: "Pan American Energy",
    provider: "Continuidad sujeta a decisión provincial",
    service: "Operación, mantenimiento, abandono de pozos y soporte ambiental",
    basin: "Cuenca del Noroeste",
    province: "Salta",
    evidence: "La concesión vence el 25/10/2026 y el operador presentó una solicitud de renovación con inversiones y un programa de abandono de ocho a diez pozos.",
    confidence_basis: "Comunicado oficial provincial; es una renovación en evaluación y no una licitación competitiva abierta.",
  },
}, {
  article_id: "CURATED-HIDRO-FUTALEUFU-2027",
  source_url: "https://www.argentina.gob.ar/normativa/nacional/norma-429905",
  source_name: "Ministerio de Economía",
  base_end_date: "2027-09-10",
  option_end_date: null,
  expiry_label: "Futaleufú · continuidad transitoria hasta nueva contratación",
  radar_status: "OPORTUNIDAD_EN_PREPARACION",
  confidence: 97,
  finding: {
    relevant: true,
    operator: "Hidroeléctrica Futaleufú S.A. durante la transición",
    provider: "Nuevo concesionario a seleccionar",
    service: "Operación, mantenimiento, logística y soporte de infraestructura energética",
    basin: "Patagonia",
    province: "Chubut",
    evidence: "La Resolución 1498/2026 extendió la continuidad hasta el 10/09/2027 o hasta la nueva contratación y ordenó avanzar con ese procedimiento.",
    confidence_basis: "Resolución nacional vigente; falta publicación del pliego o convocatoria accionable.",
  },
}, {
  article_id: "CURATED-HIDRO-RIO-HONDO-QUIROGA-2026",
  source_url: "https://www.argentina.gob.ar/normativa/nacional/norma-428745/texto",
  source_name: "Secretaría de Energía",
  base_end_date: "2026-12-15",
  option_end_date: null,
  expiry_label: "Río Hondo y Los Quiroga · licitación internacional en preparación",
  radar_status: "OPORTUNIDAD_EN_PREPARACION",
  confidence: 96,
  finding: {
    relevant: true,
    operator: "Hidroeléctrica Río Hondo S.A. durante la transición",
    provider: "Nuevo concesionario a seleccionar",
    service: "Operación, mantenimiento y servicios auxiliares de generación",
    basin: "Sistema Río Dulce",
    province: "Santiago del Estero",
    evidence: "La Resolución 198/2026 mantiene la operación hasta el 15/12/2026 y declara la intención estatal de convocar una licitación pública nacional e internacional.",
    confidence_basis: "Resolución nacional vigente; no se localizó aún el pliego de la nueva concesión.",
  },
}, {
  article_id: "CURATED-HIDRO-LOS-NIHUILES-2026",
  source_url: "https://www.argentina.gob.ar/node/508593",
  source_name: "Gobierno nacional",
  base_end_date: "2026-12-31",
  option_end_date: null,
  expiry_label: "Los Nihuiles · licitación nacional e internacional convocada",
  radar_status: "OPORTUNIDAD_EN_CURSO_SIN_PLAZO_CONFIRMADO",
  confidence: 95,
  finding: {
    relevant: true,
    operator: "Hidroelectricidad Mendocina S.A. durante la transición",
    provider: "Nuevo concesionario y adquirente del paquete accionario a seleccionar",
    service: "Operación, mantenimiento, seguridad de presas y soporte de generación",
    basin: "Río Atuel",
    province: "Mendoza",
    evidence: "El DNU 667/2026 convocó la licitación para la concesión del sistema y la venta del 100% de Hidroelectricidad Mendocina; la transición vence como máximo el 31/12/2026.",
    confidence_basis: "Convocatoria oficial. El radar debe verificar CONTRAT.AR antes de afirmar que la recepción de ofertas sigue abierta.",
  },
}, {
  article_id: "CURATED-OFFSHORE-CAN-200-2026",
  source_url: "https://www.boletinoficial.gob.ar/detalleAviso/primera/344334/20260715",
  source_name: "Boletín Oficial de la República Argentina",
  base_end_date: null,
  option_end_date: null,
  expiry_label: "Área costa afuera CAN_200 · concurso internacional ordenado",
  radar_status: "OPORTUNIDAD_EN_PREPARACION",
  confidence: 98,
  finding: {
    relevant: true,
    operator: "A seleccionar por la Secretaría de Energía",
    provider: "Permisionario de exploración a seleccionar",
    service: "Exploración costa afuera, logística, transporte y soporte operativo",
    basin: "Cuenca Argentina Norte",
    province: "Costa afuera nacional",
    evidence: "El Decreto 590/2026 instruyó convocar un Concurso Público Internacional para adjudicar el permiso de exploración del área CAN_200 y aprobar su pliego.",
    confidence_basis: "Decreto nacional vigente; aún debe localizarse la convocatoria operativa y su cronograma.",
  },
}, {
  article_id: "CURATED-NEUQUEN-ENTRE-LOMAS-2026",
  source_url: "https://boficial.neuquen.gov.ar/LeyesDecretosDetalle?Id=424708",
  source_name: "Boletín Oficial de Neuquén",
  base_end_date: "2026-01-21",
  option_end_date: "2026-03-23",
  expiry_label: "Entre Lomas · prórroga definitiva no localizada",
  radar_status: "SEGUIMIENTO_REGULATORIO",
  confidence: 86,
  finding: {
    relevant: true,
    operator: "Vista Energy Argentina S.A.U.",
    provider: "Continuidad sujeta a decisión provincial",
    service: "Operación y servicios de yacimiento convencional",
    basin: "Cuenca Neuquina",
    province: "Neuquén",
    evidence: "El Decreto 110/2026 sólo extendió la concesión 60 días, hasta el 23/03/2026, mientras se evaluaba la prórroga solicitada.",
    confidence_basis: "Acto oficial; no se halló una decisión definitiva posterior, por lo que no debe presentarse como licitación abierta.",
  },
}, {
  article_id: "CURATED-NEUQUEN-LOS-BASTOS-2026",
  source_url: "https://infoleg.neuquen.gov.ar/LeyesDecretosDetalle?Id=424751",
  source_name: "Boletín Oficial de Neuquén",
  base_end_date: "2026-01-10",
  option_end_date: "2026-03-12",
  expiry_label: "Los Bastos · prórroga definitiva no localizada",
  radar_status: "SEGUIMIENTO_REGULATORIO",
  confidence: 86,
  finding: {
    relevant: true,
    operator: "Tecpetrol S.A.",
    provider: "Continuidad sujeta a decisión provincial",
    service: "Operación y servicios de yacimiento convencional",
    basin: "Cuenca Neuquina",
    province: "Neuquén",
    evidence: "El Decreto 152/2026 sólo extendió la concesión 60 días, hasta el 12/03/2026, sin decidir la prórroga decenal solicitada.",
    confidence_basis: "Acto oficial; no se halló una decisión definitiva posterior, por lo que requiere seguimiento regulatorio.",
  },
}] as const;
