import { z } from "zod";

export const opportunitySchema = z.object({
  relevante: z.boolean(),
  empresa: z.string(),
  empresa_prioritaria: z.boolean(),
  provincia: z.string(),
  cuenca: z.string(),
  proyecto: z.string(),
  servicios_vermaz: z.array(z.object({ servicio: z.string(), justificacion: z.string() })),
  tipo_senal: z.string(),
  score_radar: z.number().int().min(0).max(100),
  prioridad: z.enum(["Crítica", "Alta", "Media", "Baja", "Muy baja"]),
  etapa_temporal: z.enum(["Temprana", "En desarrollo", "Contratación", "Adjudicada"]),
  horizonte: z.enum(["Inmediata / 0–30 días", "Corto / 1–3 meses", "Medio / 3–6 meses", "Largo / 6–12 meses", "Futuro / +12 meses", "Sin determinar"]),
  hechos_publicados: z.array(z.string()),
  inferencias_comerciales: z.array(z.string()),
  resumen_evidencia: z.string(),
  analisis_ia: z.string(),
  area_objetivo: z.string(),
  cargo_objetivo: z.string(),
  persona_objetivo_nombre: z.string(),
  motivo_contacto: z.string(),
  buscar_en_attio: z.boolean(),
  linkedin_requerido: z.boolean(),
  mensaje_comercial_sugerido: z.string(),
  tipo_accion: z.enum(["INVESTIGAR", "BUSCAR_CONTACTO", "SEGUIR", "CONTACTAR"]),
  accion_sugerida: z.string(),
  confianza_ia: z.number().int().min(0).max(100),
});

export const opportunityJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: Object.keys(opportunitySchema.shape),
  properties: {
    relevante: { type: "boolean" }, empresa: { type: "string" }, empresa_prioritaria: { type: "boolean" },
    provincia: { type: "string" }, cuenca: { type: "string" }, proyecto: { type: "string" },
    servicios_vermaz: { type: "array", items: { type: "object", additionalProperties: false, required: ["servicio", "justificacion"], properties: { servicio: { type: "string" }, justificacion: { type: "string" } } } },
    tipo_senal: { type: "string" }, score_radar: { type: "integer", minimum: 0, maximum: 100 },
    prioridad: { type: "string", enum: ["Crítica", "Alta", "Media", "Baja", "Muy baja"] },
    etapa_temporal: { type: "string", enum: ["Temprana", "En desarrollo", "Contratación", "Adjudicada"] },
    horizonte: { type: "string", enum: ["Inmediata / 0–30 días", "Corto / 1–3 meses", "Medio / 3–6 meses", "Largo / 6–12 meses", "Futuro / +12 meses", "Sin determinar"] },
    hechos_publicados: { type: "array", items: { type: "string" } }, inferencias_comerciales: { type: "array", items: { type: "string" } },
    resumen_evidencia: { type: "string" }, analisis_ia: { type: "string" }, area_objetivo: { type: "string" }, cargo_objetivo: { type: "string" },
    persona_objetivo_nombre: { type: "string" }, motivo_contacto: { type: "string" }, buscar_en_attio: { type: "boolean" }, linkedin_requerido: { type: "boolean" },
    mensaje_comercial_sugerido: { type: "string" }, tipo_accion: { type: "string", enum: ["INVESTIGAR", "BUSCAR_CONTACTO", "SEGUIR", "CONTACTAR"] },
    accion_sugerida: { type: "string" }, confianza_ia: { type: "integer", minimum: 0, maximum: 100 },
  },
} as const;
